// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleGax
import struct Logging.Logger

extension Clients {
  final class CloudLocationFinderLogging: CloudLocationFinderStub {
    let inner: any CloudLocationFinderStub
    let logger: Logger

    public init(_ inner: any CloudLocationFinderStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-locationfinder-v1"
      logger[metadataKey: "gcp.client.service"] = "cloudlocationfinder"
      logger[metadataKey: "gcp.experimental.swift.client"] = "CloudLocationFinder"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listCloudLocations(
      request: ListCloudLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocationFinderV1.ListCloudLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listCloudLocations",
        action: {
          (r: ListCloudLocationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocationFinderV1.ListCloudLocationsResponse
          in
          return try await self.inner.listCloudLocations(request: r, options: o)
        })
    }

    public func getCloudLocation(
      request: GetCloudLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocationFinderV1.CloudLocation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getCloudLocation",
        action: {
          (r: GetCloudLocationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocationFinderV1.CloudLocation
          in
          return try await self.inner.getCloudLocation(request: r, options: o)
        })
    }

    public func searchCloudLocations(
      request: SearchCloudLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocationFinderV1.SearchCloudLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "searchCloudLocations",
        action: {
          (r: SearchCloudLocationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocationFinderV1.SearchCloudLocationsResponse
          in
          return try await self.inner.searchCloudLocations(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }
  }
}
