// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
@_spi(GoogleCloudInternal) import GoogleGax

extension Clients {
  final class CloudLocationFinderRetry: CloudLocationFinderStub {
    let inner: any CloudLocationFinderStub
    let options: GoogleGax.ClientOptions

    public init(_ inner: any CloudLocationFinderStub, options: GoogleGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func listCloudLocations(
      request: ListCloudLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocationFinderV1.ListCloudLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListCloudLocationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocationFinderV1.ListCloudLocationsResponse
          in
          return try await self.inner.listCloudLocations(request: r, options: o)
        })
    }

    public func getCloudLocation(
      request: GetCloudLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocationFinderV1.CloudLocation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetCloudLocationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocationFinderV1.CloudLocation
          in
          return try await self.inner.getCloudLocation(request: r, options: o)
        })
    }

    public func searchCloudLocations(
      request: SearchCloudLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocationFinderV1.SearchCloudLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: SearchCloudLocationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocationFinderV1.SearchCloudLocationsResponse
          in
          return try await self.inner.searchCloudLocations(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }
  }
}
