// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleGax

extension Clients {
  protocol CloudLocationFinderStub: Sendable {
    func listCloudLocations(
      request: ListCloudLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocationFinderV1.ListCloudLocationsResponse

    func getCloudLocation(
      request: GetCloudLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocationFinderV1.CloudLocation

    func searchCloudLocations(
      request: SearchCloudLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocationFinderV1.SearchCloudLocationsResponse

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location
  }
}
