// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Represents resource cloud locations.
public struct CloudLocation: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. Name of the cloud location. Unique name of the cloud location
  /// including project and location using the form:
  /// `projects/{project_id}/locations/{location}/cloudLocations/{cloud_location}`
  public var name: Swift.String = Swift.String()

  /// Output only. The containing cloud location in the strict nesting hierarchy.
  /// For example, the containing cloud location of a zone is a region.
  public var containingCloudLocation: Swift.String = Swift.String()

  /// Optional. The human-readable name of the cloud location. Example:
  /// us-east-2, us-east1.
  public var displayName: Swift.String = Swift.String()

  /// Optional. The provider of the cloud location. Values can be Google Cloud or
  /// third-party providers, including AWS, Azure, or Oracle Cloud
  /// Infrastructure.
  public var cloudProvider: CloudLocation.CloudProvider = CloudLocation.CloudProvider()

  /// Optional. The two-letter ISO 3166-1 alpha-2 code of the cloud location.
  /// Examples: US, JP, KR.
  public var territoryCode: Swift.String = Swift.String()

  /// Optional. The type of the cloud location.
  public var cloudLocationType: CloudLocation.CloudLocationType = CloudLocation.CloudLocationType()

  /// Optional. The carbon free energy percentage of the cloud location. This
  /// represents the average percentage of time customers' application will be
  /// running on carbon-free energy. See
  /// https://cloud.google.com/sustainability/region-carbon for more details.
  /// There is a difference between default value 0 and unset value. 0 means the
  /// carbon free energy percentage is 0%, while unset value means the carbon
  /// footprint data is not available.
  public var carbonFreeEnergyPercentage: Swift.Float? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CloudLocation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CloudLocation().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let containingCloudLocation = CodingKeys(stringValue: "containingCloudLocation")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let cloudProvider = CodingKeys(stringValue: "cloudProvider")
    static let territoryCode = CodingKeys(stringValue: "territoryCode")
    static let cloudLocationType = CodingKeys(stringValue: "cloudLocationType")
    static let carbonFreeEnergyPercentage = CodingKeys(stringValue: "carbonFreeEnergyPercentage")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "containingCloudLocation",
      "displayName",
      "cloudProvider",
      "territoryCode",
      "cloudLocationType",
      "carbonFreeEnergyPercentage",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .containingCloudLocation)
    {
      self.containingCloudLocation = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(
      CloudLocation.CloudProvider.self, forKey: .cloudProvider)
    {
      self.cloudProvider = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .territoryCode) {
      self.territoryCode = value
    }
    if let value = try container.decodeIfPresent(
      CloudLocation.CloudLocationType.self, forKey: .cloudLocationType)
    {
      self.cloudLocationType = value
    }
    self.carbonFreeEnergyPercentage = try container.decodeIfPresent(
      Swift.Float.self, forKey: .carbonFreeEnergyPercentage)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.containingCloudLocation, forKey: .containingCloudLocation)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.cloudProvider, forKey: .cloudProvider)
    try container.encode(self.territoryCode, forKey: .territoryCode)
    try container.encode(self.cloudLocationType, forKey: .cloudLocationType)
    try container.encodeIfPresent(
      self.carbonFreeEnergyPercentage, forKey: .carbonFreeEnergyPercentage)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type of the cloud provider. This enum lists all possible providers of
  /// cloud locations.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum CloudProvider: Codable, Equatable, Sendable {
    /// Unspecified type.
    case unspecified
    /// Cloud provider type for Google Cloud.
    case gcp
    /// Cloud provider type for AWS.
    case aws
    /// Cloud provider type for Azure.
    case azure
    /// Cloud provider type for OCI.
    case oci
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .gcp: return 1
      case .aws: return 2
      case .azure: return 3
      case .oci: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CLOUD_PROVIDER_UNSPECIFIED"
      case .gcp: return "CLOUD_PROVIDER_GCP"
      case .aws: return "CLOUD_PROVIDER_AWS"
      case .azure: return "CLOUD_PROVIDER_AZURE"
      case .oci: return "CLOUD_PROVIDER_OCI"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:CloudProvider/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CLOUD_PROVIDER_UNSPECIFIED": self = .unspecified
      case "CLOUD_PROVIDER_GCP": self = .gcp
      case "CLOUD_PROVIDER_AWS": self = .aws
      case "CLOUD_PROVIDER_AZURE": self = .azure
      case "CLOUD_PROVIDER_OCI": self = .oci
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:CloudProvider/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .gcp
      case 2: self = .aws
      case 3: self = .azure
      case 4: self = .oci
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("CLOUD_PROVIDER_UNSPECIFIED")
      case .gcp: return try container.encode("CLOUD_PROVIDER_GCP")
      case .aws: return try container.encode("CLOUD_PROVIDER_AWS")
      case .azure: return try container.encode("CLOUD_PROVIDER_AZURE")
      case .oci: return try container.encode("CLOUD_PROVIDER_OCI")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The type of the cloud location. This enum lists all possible categories of
  /// cloud locations.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum CloudLocationType: Codable, Equatable, Sendable {
    /// Unspecified type.
    case unspecified
    /// CloudLocation type for region.
    case region
    /// CloudLocation type for zone.
    case zone
    /// CloudLocation type for region extension.
    case regionExtension
    /// CloudLocation type for Google Distributed Cloud Connected Zone.
    case gdccZone
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .region: return 1
      case .zone: return 2
      case .regionExtension: return 3
      case .gdccZone: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CLOUD_LOCATION_TYPE_UNSPECIFIED"
      case .region: return "CLOUD_LOCATION_TYPE_REGION"
      case .zone: return "CLOUD_LOCATION_TYPE_ZONE"
      case .regionExtension: return "CLOUD_LOCATION_TYPE_REGION_EXTENSION"
      case .gdccZone: return "CLOUD_LOCATION_TYPE_GDCC_ZONE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:CloudLocationType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CLOUD_LOCATION_TYPE_UNSPECIFIED": self = .unspecified
      case "CLOUD_LOCATION_TYPE_REGION": self = .region
      case "CLOUD_LOCATION_TYPE_ZONE": self = .zone
      case "CLOUD_LOCATION_TYPE_REGION_EXTENSION": self = .regionExtension
      case "CLOUD_LOCATION_TYPE_GDCC_ZONE": self = .gdccZone
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:CloudLocationType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .region
      case 2: self = .zone
      case 3: self = .regionExtension
      case 4: self = .gdccZone
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("CLOUD_LOCATION_TYPE_UNSPECIFIED")
      case .region: return try container.encode("CLOUD_LOCATION_TYPE_REGION")
      case .zone: return try container.encode("CLOUD_LOCATION_TYPE_ZONE")
      case .regionExtension: return try container.encode("CLOUD_LOCATION_TYPE_REGION_EXTENSION")
      case .gdccZone: return try container.encode("CLOUD_LOCATION_TYPE_GDCC_ZONE")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.locationfinder.v1.CloudLocation"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
