// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleCloudLocation
@_spi(GoogleCloudInternal) public import GoogleGax

/// Service describing handlers for resources
///
/// @Snippet(path: "CloudLocationFinderQuickstart")
public final class CloudLocationFinderClient: Clients.CloudLocationFinderProtocol, Sendable {
  let inner: any Clients.CloudLocationFinderStub

  /// Creates a new `CloudLocationFinderClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.CloudLocationFinderStub = try Clients.CloudLocationFinderTransport(
      options)
    inner = Clients.CloudLocationFinderRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.CloudLocationFinderLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Lists cloud locations under a given project and location.
  ///
  /// @Snippet(path: "CloudLocationFinder_ListCloudLocations")
  public func listCloudLocations(
    request: ListCloudLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocationFinderV1.ListCloudLocationsResponse {
    try await self.inner.listCloudLocations(request: request, options: options)
  }

  /// Lists cloud locations under a given project and location.
  ///
  /// @Snippet(path: "CloudLocationFinder_ListCloudLocations")
  public func listCloudLocations(
    byItem: ListCloudLocationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<CloudLocation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocationFinderV1.ListCloudLocationsResponse
      in
      var request = byItem
      request.pageToken = token
      return try await self.listCloudLocations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Retrieves a resource containing information about a cloud location.
  ///
  /// @Snippet(path: "CloudLocationFinder_GetCloudLocation")
  public func getCloudLocation(
    request: GetCloudLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocationFinderV1.CloudLocation {
    try await self.inner.getCloudLocation(request: request, options: options)
  }

  /// Searches for cloud locations from a given source location.
  ///
  /// @Snippet(path: "CloudLocationFinder_SearchCloudLocations")
  public func searchCloudLocations(
    request: SearchCloudLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocationFinderV1.SearchCloudLocationsResponse {
    try await self.inner.searchCloudLocations(request: request, options: options)
  }

  /// Searches for cloud locations from a given source location.
  ///
  /// @Snippet(path: "CloudLocationFinder_SearchCloudLocations")
  public func searchCloudLocations(
    byItem: SearchCloudLocationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<CloudLocation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocationFinderV1.SearchCloudLocationsResponse
      in
      var request = byItem
      request.pageToken = token
      return try await self.searchCloudLocations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "CloudLocationFinder_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "CloudLocationFinder_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "CloudLocationFinder_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `CloudLocationFinderClient`.
  ///
  /// To mock `CloudLocationFinderClient` change your functions to receive
  /// `some CloudLocationFinderProtocol` or `any CloudLocationFinderProtocol`
  /// and pass a mock implementation in your tests.
  public protocol CloudLocationFinderProtocol {
    /// See `CloudLocationFinderClient.listCloudLocations`.
    func listCloudLocations(request: ListCloudLocationsRequest) async throws
      -> GoogleCloudLocationFinderV1.ListCloudLocationsResponse

    /// See `CloudLocationFinderClient.listCloudLocations`.
    func listCloudLocations(
      byItem: ListCloudLocationsRequest
    ) -> any AsyncSequence<CloudLocation, Swift.Error>

    /// See `CloudLocationFinderClient.listCloudLocations`.
    func listCloudLocations(
      parent: Swift.String,
    ) -> any AsyncSequence<CloudLocation, Swift.Error>

    /// See `CloudLocationFinderClient.getCloudLocation`.
    func getCloudLocation(request: GetCloudLocationRequest) async throws
      -> GoogleCloudLocationFinderV1.CloudLocation

    /// See `CloudLocationFinderClient.getCloudLocation`.
    func getCloudLocation(
      name: Swift.String,
    ) async throws -> GoogleCloudLocationFinderV1.CloudLocation

    /// See `CloudLocationFinderClient.searchCloudLocations`.
    func searchCloudLocations(request: SearchCloudLocationsRequest) async throws
      -> GoogleCloudLocationFinderV1.SearchCloudLocationsResponse

    /// See `CloudLocationFinderClient.searchCloudLocations`.
    func searchCloudLocations(
      byItem: SearchCloudLocationsRequest
    ) -> any AsyncSequence<CloudLocation, Swift.Error>

    /// See `CloudLocationFinderClient.searchCloudLocations`.
    func searchCloudLocations(
      parent: Swift.String,
      sourceCloudLocation: Swift.String,
      query: Swift.String,
    ) -> any AsyncSequence<CloudLocation, Swift.Error>

    /// See `CloudLocationFinderClient.listLocations`.
    func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse

    /// See `CloudLocationFinderClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `CloudLocationFinderClient.getLocation`.
    func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location

    /// See `CloudLocationFinderClient.listCloudLocations`.
    func listCloudLocations(
      request: ListCloudLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocationFinderV1.ListCloudLocationsResponse

    /// See `CloudLocationFinderClient.listCloudLocations`.
    func listCloudLocations(
      byItem: ListCloudLocationsRequest, options: GoogleGax.RequestOptions
    ) -> any AsyncSequence<CloudLocation, Swift.Error>

    /// See `CloudLocationFinderClient.getCloudLocation`.
    func getCloudLocation(
      request: GetCloudLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocationFinderV1.CloudLocation

    /// See `CloudLocationFinderClient.searchCloudLocations`.
    func searchCloudLocations(
      request: SearchCloudLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocationFinderV1.SearchCloudLocationsResponse

    /// See `CloudLocationFinderClient.searchCloudLocations`.
    func searchCloudLocations(
      byItem: SearchCloudLocationsRequest, options: GoogleGax.RequestOptions
    ) -> any AsyncSequence<CloudLocation, Swift.Error>

    /// See `CloudLocationFinderClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `CloudLocationFinderClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `CloudLocationFinderClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location
  }
}

// Default implementations
extension Clients.CloudLocationFinderProtocol {
  public func listCloudLocations(request: ListCloudLocationsRequest) async throws
    -> GoogleCloudLocationFinderV1.ListCloudLocationsResponse
  {
    try await self.listCloudLocations(request: request, options: .init())
  }

  public func listCloudLocations(
    request: ListCloudLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocationFinderV1.ListCloudLocationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listCloudLocations(
    byItem: ListCloudLocationsRequest
  ) -> any AsyncSequence<CloudLocation, Swift.Error> {
    self.listCloudLocations(byItem: byItem, options: .init())
  }

  public func listCloudLocations(
    byItem: ListCloudLocationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<CloudLocation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocationFinderV1.ListCloudLocationsResponse
      in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listCloudLocations(
    parent: Swift.String,
  ) -> any AsyncSequence<CloudLocation, Swift.Error> {
    let request = ListCloudLocationsRequest().with {
      $0.parent = parent
    }
    return self.listCloudLocations(byItem: request)
  }

  public func getCloudLocation(request: GetCloudLocationRequest) async throws
    -> GoogleCloudLocationFinderV1.CloudLocation
  {
    try await self.getCloudLocation(request: request, options: .init())
  }

  public func getCloudLocation(
    request: GetCloudLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocationFinderV1.CloudLocation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getCloudLocation(
    name: Swift.String,
  ) async throws -> GoogleCloudLocationFinderV1.CloudLocation {
    let request = GetCloudLocationRequest().with {
      $0.name = name
    }
    return try await self.getCloudLocation(request: request)
  }

  public func searchCloudLocations(request: SearchCloudLocationsRequest) async throws
    -> GoogleCloudLocationFinderV1.SearchCloudLocationsResponse
  {
    try await self.searchCloudLocations(request: request, options: .init())
  }

  public func searchCloudLocations(
    request: SearchCloudLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocationFinderV1.SearchCloudLocationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func searchCloudLocations(
    byItem: SearchCloudLocationsRequest
  ) -> any AsyncSequence<CloudLocation, Swift.Error> {
    self.searchCloudLocations(byItem: byItem, options: .init())
  }

  public func searchCloudLocations(
    byItem: SearchCloudLocationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<CloudLocation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocationFinderV1.SearchCloudLocationsResponse
      in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func searchCloudLocations(
    parent: Swift.String,
    sourceCloudLocation: Swift.String,
    query: Swift.String,
  ) -> any AsyncSequence<CloudLocation, Swift.Error> {
    let request = SearchCloudLocationsRequest().with {
      $0.parent = parent
      $0.sourceCloudLocation = sourceCloudLocation
      $0.query = query
    }
    return self.searchCloudLocations(byItem: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleGax.RequestError.unimplemented
  }
}
